### ISSUE TITLE
Error when run project

### ISSUE THREAD

**Issue by ferrari-tran** [thuanmb/react-mapbox-gl-cluster#19] opened 2022-07-21 08:34 UTC
`./node_modules/react-mapbox-gl-cluster/node_modules/react-mapbox-gl-spiderifier/dist/components/MappedComponent.js
Module not found: Can't resolve '/Users/thuanbui/source_code/react-mapbox-gl-spiderifier/node_modules/@babel/runtime/helpers/esm/classCallCheck' in '/Users/laoton/Workspaces/Study/mapbox-cluster/node_modules/react-mapbox-gl-cluster/node_modules/react-mapbox-gl-spiderifier/dist/components'`

Did you build it again? I saw your computer's name here

**Comment by thuanmb** [comment] 2022-08-03 02:49
Which version are you running? I cannot reproduce your issue. Can you share a reproducible repo?

**Comment by thuanmb** [comment] 2023-02-18 03:22
Because the issue's creator has not responded for more than 6 months, closing the the issue as "won't fix". Please help to reopen it when you have any update @ferrari-tran!
Thanks!

**Closed as completed by thuanmb** 2023-02-18 03:22 UTC
